name: find_it
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  flutter_localizations:
    sdk: flutter
  slang_flutter: ^4.0.0
  slang: ^4.0.0
  get_it: ^8.0.0
  injectable: ^2.5.0
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  freezed_annotation: ^2.4.4
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  mutex: ^3.1.0
  flutter_web_auth_2: ^4.0.2
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_osm_plugin: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  dotenv: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - .env
